import React, { useState } from "react";
import NotFound from "@/pages/NotFound";
import { Button } from "@/components/ui/button";
import { ProjectView, PlanningView } from "@/components/WriterStudio";
import { FileText, ShieldCheck, Sparkles, Target, UsersRound } from "lucide-react";

type PreviewView = "project" | "planning" | "manuscript" | "prepare" | "security";
type Book = React.ComponentProps<typeof ProjectView>["book"];

const previewBook: Book = { id: "preview-book", title: "A cidade entre marés", status: "planning", targetWordCount: 50000, updatedAt: Date.now(), nodes: [{ id: "preview-node", title: "Capítulo 1", kind: "chapter", content: "", updatedAt: Date.now() }], planning: { characters: [{ id: "c1", name: "Lia", role: "Protagonista", notes: "" }], locations: [{ id: "l1", name: "Porto velho", atmosphere: "Nebuloso", notes: "" }], timeline: [{ id: "t1", title: "A partida", date: "Noite 1", description: "" }] }, nextSteps: ["Definir a sinopse"] };

export default function EditorialPreview() {
  const [view, setView] = useState<PreviewView>(new URLSearchParams(window.location.search).get("view") as PreviewView || "project");
  const [book, setBook] = useState(previewBook);
  if (!import.meta.env.DEV) return <NotFound />;
  return <div className="min-h-screen bg-background text-foreground"><header className="border-b border-border/70 bg-background"><div className="mx-auto flex max-w-7xl items-center gap-2 px-5 py-3"><span className="mr-3 font-serif text-lg">Shakstory · Preview interno</span>{(["project", "planning", "manuscript", "prepare", "security"] as PreviewView[]).map(item => <Button key={item} variant={view === item ? "default" : "ghost"} size="sm" onClick={() => setView(item)}>{item === "project" ? <><Target className="mr-2 h-3.5 w-3.5" />Projeto</> : item === "planning" ? <><UsersRound className="mr-2 h-3.5 w-3.5" />Planejar</> : item === "manuscript" ? <><FileText className="mr-2 h-3.5 w-3.5" />Manuscrito</> : item === "security" ? <><ShieldCheck className="mr-2 h-3.5 w-3.5" />Segurança</> : <><Sparkles className="mr-2 h-3.5 w-3.5" />Preparar</>}</Button>)}</div></header><main className="mx-auto max-w-7xl px-5 py-10">{view === "project" && <ProjectView book={book} onNavigate={value => value !== "editor" && value !== "library" && value !== "account" && setView(value)} onUpdate={patch => setBook(current => ({ ...current, ...patch }))} />}{view === "planning" && <PlanningView book={book} onUpdate={planning => setBook(current => ({ ...current, planning }))} />}{view === "manuscript" && <section className="mx-auto max-w-3xl"><p className="font-mono text-[10px] uppercase tracking-[0.16em] text-primary">Manuscrito opcional</p><h1 className="mt-2 font-serif text-4xl">Capítulo 1</h1><p className="mt-3 text-sm leading-6 text-muted-foreground">Esta área só é aberta quando o autor decide escrever ou revisar.</p><textarea className="mt-8 min-h-[27rem] w-full resize-none border-0 bg-transparent font-serif text-lg leading-[1.9] outline-none" placeholder="Comece onde a história pede." readOnly /></section>}{view === "prepare" && <section className="mx-auto max-w-4xl"><p className="font-mono text-[10px] uppercase tracking-[0.16em] text-primary">Preparação editorial</p><h1 className="mt-2 font-serif text-4xl">Leve o projeto até a capa.</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-muted-foreground">Metadados e pré-visualização estrutural, sem alterar capítulos.</p></section>}{view === "security" && <section className="mx-auto max-w-4xl"><p className="font-mono text-[10px] uppercase tracking-[0.16em] text-primary">Segurança</p><h1 className="mt-2 font-serif text-4xl">Proteção antivírus interna</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-muted-foreground">A tela completa de sessões e credenciais exige autenticação do proprietário.</p></section>}</main></div>;
}
